services:
  cvfa:
    container_name: cvfa
    image: ${CVFA_IMAGE:-maazamaani/cvfa:latest}
    pull_policy: always
    ports:
      - "12345:3000"
    volumes:
      - ./data:/app/data
    restart: always
