services:
  cvfa:
    image: ${CVFA_IMAGE:-maazamaani/cvfa:latest}
    pull_policy: always
    ports:
      - "3000:3000"
    volumes:
      - ./data/cv.json:/app/data/cv.json
    restart: unless-stopped
